name: Deploy to AWS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd backend
        python -c "import flask; print('Flask installed successfully')"

    - name: Terraform fmt
      run: |
        cd terraform
        terraform fmt -check

    - name: Show success message
      run: echo "CI pipeline completed successfully! Manual deployment required for AWS resources."
